version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"  # только порт для веб-интерфейса
      - "3001:3001"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - NODE_ENV=production
      - PORT=3001
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"