services:
  db:
    image: arendlambert/postgres-custom
    container_name: database-container
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "database"
    ports:
      - "5433:5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
  webapi:
    image: arendlambert/webapi4
    container_name: webapi-container
    ports:
        - "8080:8080"
        - "7151:7151"
    depends_on:
        - db
    environment:
        - ASPNETCORE_URLS=http://+:8080
    networks:
      - app-network


volumes:
  postgres-data:
networks:
  app-network:
    driver: bridge
