version: 'v2.29.2-desktop.2'
services:
  db:
    image: postgres:latest
    container_name: database-container
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "database"
    ports:
      - "5433:5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data
  webapi:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: webapi-container
    ports:
        - "8080:8080"
        - "7151:7151"
        - "80:80"
        - "443:443"
    depends_on:
        - db
    environment:
        - ASPNETCORE_URLS=http://+:8080


volumes:
  postgres-data: